### ISSUE TITLE
Cannot read property 'role' of undefined

### ISSUE THREAD

**Issue by YuriFontella** [hsynlms/fastify-guard#1]
preHandler: [fastify.guard.role(['admin'])] -> In this way, preHandler is already called upon startup. And not on the route call.

![image](https://user-images.githubusercontent.com/4920619/99476340-240d8680-292f-11eb-9afc-d63e7f089f50.png)

Inside the preHandler function... fastify.guard.role(['admin']) don't work.

If you can correct me if I did something wrong.

"fastify": "^3.8.0"

**Comment by hsynlms** [comment]
Hello @YuriFontella 

fastify-guard checks user roles and scopes in the `user` object defined in the **request**. If it does not exist, the plugin throws exceptions.

I attached an example below. You can parse and set the request user object before preHandler hook runs. To do that please check [this documentation](https://www.fastify.io/docs/latest/Lifecycle/) which tells us more about it.

```js
request.user = {
  name: 'john doe',
  age: 28,
  roles: [...],
  scopes: [..]
}
```

Could you please be sure that when this preHandler (in the image of yours) function is invoked, the user object does exist in the request.

**Comment by YuriFontella** [comment]
![image](https://user-images.githubusercontent.com/4920619/99546765-8600d700-2995-11eb-973f-5e507f39c307.png)
![image](https://user-images.githubusercontent.com/4920619/99546829-987b1080-2995-11eb-9963-358039a676b4.png)
![image](https://user-images.githubusercontent.com/4920619/99546882-a9c41d00-2995-11eb-9225-bb9e2e6b89e8.png)

The error happens without having made a request for the route. The route preHandler runs when I start the server.
The addHook has not been run before.

**Comment by hsynlms** [comment]
@YuriFontella it looks like the plugin has not been initialized at that moment so `guard` decorator is undefined. Are you setting up Fastify Server in the below order?

https://www.fastify.io/docs/latest/Getting-Started/#loading-order-of-your-plugins

**Comment by YuriFontella** [comment]
So that's it, according to the life cycle, hooks come after plugins.
And how would I do to authenticate the user before registering the plugin?

https://gist.github.com/YuriFontella/1a3bc5a2da9ee005aa5fc3f44b247af4 demo project

![image](https://user-images.githubusercontent.com/4920619/99556275-147a5600-29a0-11eb-9dee-816db53fa35d.png)
![image](https://user-images.githubusercontent.com/4920619/99556327-252acc00-29a0-11eb-820b-943f106998b0.png)

This is what I find very strange

**Comment by YuriFontella** [comment]
```
fastify.after(() => {

	fastify.get('/', {
		preHandler: [fastify.guard.role('guest')]
	},

	async (request, reply) => {
		let data = await fastify.knex .select() .from('users')
		reply.send(data)
	})

})
```

it worked using the after function ... I don't know if this was the best solution.

Thanks for attention.

**Comment by hsynlms** [comment]
I am glad to hear you solved the issue. If I were you I would use async/await instead of using after, ready functions in the project.
