### ISSUE TITLE
Wrong documentation

### ISSUE THREAD

**Issue by DesimirDimitrov** [hsynlms/fastify-guard#13]
In the README.md

This code doesn't work:

`{ preHandler: [fastify.guard.role(['cto', 'admin'])] },`

Instead it should be without []

`{ preHandler: [fastify.guard.role('cto', 'admin')] },`

**Comment by Pustinyak** [comment]
`role(['editor', 'admin'])` - can only be called by users who have 'editor' **AND** 'admin' role
`role('editor', 'admin')` - can only be called by users who have 'editor' **OR** 'admin' roles

**Comment by FKPSC** [comment]
The difference is only documented in the comments of the example and is apparently easy to miss.

I just spent 1 whole hour trying to figure out what was wrong with my code.

I will submit a PR later to highlight this very important different in argument shape.

**Comment by hsynlms** [comment]
@FKPSC Looking forward for the PR.
