### ISSUE TITLE
allow user.role to be string 

### ISSUE THREAD

**Issue by MkLHX** [hsynlms/fastify-guard#17]
Hello, 

Thank you for this plugin it could be useful for my project.

I'm facing an issue because user.role is stored as a string in the database and I can't change it.

Regarding the logic on checkScopeAndRole and hasScopeAndRole methods is it possible to allow user.role to be string not array ?

the thing needed is to add this statement : 

```
  if (typeof permissions === 'string' && property === 'roleProperty') {
    permissions = permissions.split(' ')
  }
```
here https://github.com/hsynlms/fastify-guard/blob/main/src/index.js#L37 
and here https://github.com/hsynlms/fastify-guard/blob/main/src/index.js#L92
Like you're currently doing for scopeProperty.

I think the readme needs to be updated regarding roles parameters for .role() methods, it is still says we can use roles('admin', 'cto'), but the types claim for string[].

**Comment by hsynlms** [comment]
Hello @MkLHX 

Can you please check the main branch? [This commit](https://github.com/hsynlms/fastify-guard/commit/3bcfd4e9b48f3b4cba037c747a1a8b164a771d59) might be a solution for you.

**Comment by hsynlms** [comment]
@MkLHX did it resolve the issue you faced?

**Comment by MkLHX** [comment]
Hello @hsynlms I'll try today. Sorry for the delay

**Comment by hsynlms** [comment]
@MkLHX any update?

**Comment by MkLHX** [comment]
Hello @hsynlms I tried to use main branch code but I'm using fastify 4.29 and fastify-guard from branch expect fastify 5.0.

I can't migrate on fastify 5.0 for now. what workaround is available ?

**Comment by hsynlms** [comment]
@MkLHX I released a new version which is a patch for v2. Can you please install v2.0.2?

**Comment by hsynlms** [comment]
I am going to close the issue. If it still happens please open a new one.

**Comment by MkLHX** [comment]
hello @hsynlms, I understand.
I'm off still for 5 days. 
I will try to use your plugin next weekend and give you feedback.

**Comment by hsynlms** [comment]
@MkLHX thank you. Do not hesitate to contact me. Happy holidays.
